### ISSUE TITLE
Accidental crash 

### ISSUE THREAD

**Issue by robvanmieghem** [hyperstake/HyperStake#16]
************************
ETRKEPTION: NSt3__18ios_base7failureE
CDataStream::ignore() : end of data: unspecified iostream_category error
HyperStake in ThreadMessageHandler()

libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: CDataStream::ignore() : end of data: unspecified iostream_category error
Abort trap: 6

**Comment by robvanmieghem** [comment]
https://github.com/hyperstake/HyperStake/blob/master/src/main.cpp#L3794

Besides the fact that "Copy message to its own buffer" is no longer present in the latest bitcoin code, this is odd. Seems like nMessageSize is not correct even though it is checked before.

**Comment by vmlemon** [comment]
Looks like I can reproduce this error, or something similar using the 32-bit client, running on an x86--64 build off Windows 8.1:

```
ERROR: CheckProofOfStake() : INFO: check kernel failed on coinstake 6173ce03697177dc4b28df2df92784112bbb18eea34492fdd88e3226b20547eb, hashProof=f805075e4b09ef8301696eefb1b4ea0469b92a4dc9b4df0e9768b0d9e87ffe25
WARNING: ProcessBlock(): check proof-of-stake failed for block e911faebe122fa0f34900b7e803f530272cd68503446329e6a47c045ff98d473
INFO: Waiting 24 sec which is too long. Sending GetBlocks(0)
received block f01be1e534766efb0e01
ERROR: CheckProofOfStake() : INFO: check kernel failed on coinstake f805960180f6adb46c5f3e25d5c18aeb66cfe0b39f5af2b076d6c2501b741234, hashProof=01f1b49a16aa20d1c45b931f1a19e0a305dcf2efe5055b8bb0f855c844498780
WARNING: ProcessBlock(): check proof-of-stake failed for block f01be1e534766efb0e01a065ebe6631c50463df18a13c1fa56357cbdc528571a
INFO: Waiting 24 sec which is too long. Sending GetBlocks(0)
trying connection 182.66.11.226:18775 lastseen=17.1hrs
connection timeout
trying connection 93.215.74.60:18775 lastseen=11.2hrs
connection timeout
trying connection 87.126.175.237:18775 lastseen=6.1hrs
connection timeout
trying connection 217.66.156.100:18775 lastseen=7.7hrs
connection timeout
received block 94a3a2c221ab240d1f3f
ProcessBlock: ORPHAN BLOCK, prev=6a99110ac3c118bb7edb
trying connection 97.97.227.235:18775 lastseen=7.9hrs
socket send error 10054
disconnecting node 54.234.181.73:18775


******* exception encountered *******


************************
ETRKEPTION: NSt8ios_base7failureE       
CDataStream::ignore() : end of data       
C:\Users\TYSON_~1\AppData\Local\Temp\Rar$EXa0.068\HyperStake-qt.exe in ThreadMessageHandler()       

connection timeout
trying connection 92.23.23.232:18775 lastseen=101.5hrs
```

**Comment by presstab** [comment]
I found the commit where this is taken out of the code. I don't see any reason why we should not update to this commit.

https://github.com/litecoin-project/litecoin/commit/607dbfdeaf7ec053d959c47c125d60c0b7e7216a

**Comment by robvanmieghem** [comment]
Fully agree

**Comment by presstab** [comment]
Added two updates, and will see if I can port over some more of them over time. Question now is whether or not this actually solves the problem or if it will manifest somewhere else. My wallet is behaving normally, but I never had this problem to begin with.

https://github.com/hyperstake/HyperStake/commit/26e5706c14409f5d3419cfc0fc3d58f47b48cf9b
https://github.com/hyperstake/HyperStake/commit/2815c2de45c8170f30febcac252a2f3f327d40fc
