### ISSUE TITLE
GenesisBlock Error loading client in --testnet

### ISSUE THREAD

**Issue by Stoner19** [hyperstake/HyperStake#23]
attempted to run windows client in --testnet

ended up with this error: 
![screen shot 2015-04-01 at 9 08 25 pm](https://cloud.githubusercontent.com/assets/8030643/6957121/21962cf2-d8b5-11e4-8b21-85fda3676283.png)

Link to src/main.cpp line 2686: https://github.com/HyperStake/HyperStake/blob/master/src/main.cpp#L2686

**Comment by presstab** [comment]
Not the correct version of the client
