### ISSUE TITLE
Fee Calculation

### ISSUE THREAD

**Issue by jonprints** [hyperstake/HyperStake#24]
I have noticed that fee calculation seems to calculate incorrectly when sending the same amount up to the hundredth decimal place. I've noticed this when selecting blocks to re-size for staking, but it seems to happen no matter how many blocks are chosen. As long as you match the full currency amount with the decimal amount up to the hundredth place, it seems to give a drastically different fee amount. The examples are as follows. This is with the HyperStake QT Wallet, V1.1

PS: This seems to be a QT wide issue, it exists in all other QT versions I have tried up to 5.3.1. No matter what the coins typical fee is, it seems to take the remainder of the decimals as the fee if the same amount up to the hundredth is typed in as the send amount.  

Example 1 (One Block)

Selected Block Size: 2267.890821 HYP
Send Amount: 2267.89 (Fee calculated as .000811)
Send Amount: 2267.88 (Fee calculated as .00001)
Send Amount: 1267.89 (Fee calculated as .00001)

Example 2 (One Block)

Selected Block Size: 2934.561643 HYP
Send Amount: 2934.56 (Fee calculated as .001633)
Send Amount: 2934.55 (Fee calculated as .00001)
Send Amount: 1934.56 (Fee calculated as .00001)

Example 3 (Two Blocks)

Selected Block Sizes: 2254.50 HYP & 2260.031643 HYP (4514.531633 HYP total)
Send Amount: 4514.53 (Fee calculated as .001633)
Send Amount: 4514.52 (Fee calculated as .00001)
Send Amount: 1514.53 (Fee calculated as .00001)

**Comment by presstab** [comment]
Took me a second to remember how the fee code works, but this is actually intentional and is part of standard peercoin clients. If your change is less than the min_tx_amount (the same thing as the minimum fee) then it gets assigned automatically as part of the fee.

https://github.com/hyperstake/HyperStake/blob/master/src/wallet.cpp#L1427

**Comment by jonprints** [comment]
Ok, I understand. It was the disparity between the original fee amount and the amount it changed to that really made me question it. I guess that dust is dust when it comes down to it. Thanks press!
