### ISSUE TITLE
Change not immediately available 

### ISSUE THREAD

**Issue by saddam213** [hyperstake/HyperStake#37]
After sending a withdraw the change is not immediately available in the balance so subsequent withdraws fail with "Insufficient Funds" warning.

Waiting 10-20min the funds are then available.

Is this fixable? or is it by design, I can setup a 1 withdraw per 20min limiter, however this could cause a backlog if many people withdraw from the exchange at the same time.

Example: (waited 10-20min between errors)
./HYP sendtoaddress p6o1JmKVDW2fGAsBH1WKKJTepM5QzyTGQH 15000
6c844dccb50c0c9cfb106261e124614d6e1a3e4cca1a55aad99db2759da25217

./HYP sendtoaddress p6o1JmKVDW2fGAsBH1WKKJTepM5QzyTGQH 15000
accc0ca73c91fdf726dc3cad004464927a76599db90c510e21ba49f325079d7c

./HYP sendtoaddress p6o1JmKVDW2fGAsBH1WKKJTepM5QzyTGQH 15000
error: {"code":-4,"message":"Insufficient funds"}

./HYP sendtoaddress p6o1JmKVDW2fGAsBH1WKKJTepM5QzyTGQH 15000
507f1bcf87fbbdbbe0ae0f5657784e7c32de5bc23e81c248dd4665994437ca9f

./HYP sendtoaddress p6o1JmKVDW2fGAsBH1WKKJTepM5QzyTGQH 15000
error: {"code":-4,"message":"Insufficient funds"}

./HYP sendtoaddress p6o1JmKVDW2fGAsBH1WKKJTepM5QzyTGQH 15000
ec42b83b8637cca6d3ded67be31dbf95bb2c358b9ade3f812aae9e10760e0d7d

./HYP sendtoaddress p6o1JmKVDW2fGAsBH1WKKJTepM5QzyTGQH 15000
error: {"code":-4,"message":"Insufficient funds"}

./HYP sendtoaddress p6o1JmKVDW2fGAsBH1WKKJTepM5QzyTGQH 15000
4e6d249889f28101f289361584e2a79918a867cc791be933c6dfd3d06a3ef4e1

./HYP sendtoaddress p6o1JmKVDW2fGAsBH1WKKJTepM5QzyTGQH 15000
error: {"code":-4,"message":"Insufficient funds"}

**Comment by presstab** [comment]
From my testing, this should resolve the problem https://github.com/hyperstake/HyperStake/commit/c91f0b944353430afa969a7d1d7da0d03f0dda66

Single UTXO wallet:

./src/hyperstaked sendtoaddress pRbwpBsgumVu2pUA4u2BajC9NU5HEQ7Xuq 10
8940c4914a422c6143f917d1e27fb62a4903b4501a1e403ed1bde302839f86e8

./src/hyperstaked sendtoaddress pRbwpBsgumVu2pUA4u2BajC9NU5HEQ7Xuq 10
21b1bcc16ef294ca98a640b8330ccb858905d356d370dba905cc508756c8aa89

./src/hyperstaked sendtoaddress pRbwpBsgumVu2pUA4u2BajC9NU5HEQ7Xuq 10
ce42476fffac626404127ef1eb933376206541c6a123bd4092265774437373b7

**Comment by saddam213** [comment]
Fix works perfectly, thank you so much for the quick fix and resopnse

Cheers
Adam
