### ISSUE TITLE
Error dialog during startup

### ISSUE THREAD

**Issue by robvanmieghem** [hyperstake/HyperStake#5]
Since upgrading to 1.0.7 on osx yosemite the qt client is giving an error on startup. Seems to work just fine after confirming though.

![screen shot 2015-01-31 at 22 00 09](https://cloud.githubusercontent.com/assets/3511318/5989815/d461a4d8-a994-11e4-8e21-ef35d2a45e33.png)

A "Repair Wallet" initially crashed the wallet, but it does not do much after a restart but the error keeps popping up.

debug.log shows the stacktrace:

******* exception encountered *******
0   hyperstake-qt                       0x0000000109a62d9f _Z13LogStackTracev + 79
1   hyperstake-qt                       0x0000000109a430ec _ZN11CDataStream8setstateEsPKc + 108
2   hyperstake-qt                       0x0000000109a42e7f _ZN11CDataStream4readEPci + 255
3   hyperstake-qt                       0x0000000109a42a18 _Z11UnserializeI11CDataStreamcEvRT_RNSt3__112basic_stringIT0_NS3_11char_traitsIS5_EENS3_9allocatorIS5_EEEEii + 344
4   hyperstake-qt                       0x0000000109bb6228 _ZN11CDataStreamrsINSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEERS_RT_ + 56
5   hyperstake-qt                       0x0000000109cd1b32 _Z12ReadKeyValueP7CWalletR11CDataStreamS2_RiRNSt3__16vectorI7uint256NS4_9allocatorIS6_EEEERbSB_RNS4_12basic_stringIcNS4_11char_traitsIcEENS7_IcEEEESH_ + 9794
6   hyperstake-qt                       0x0000000109cd27ea _ZN9CWalletDB10LoadWalletEP7CWallet + 1738
7   hyperstake-qt                       0x0000000109d43e7b _ZN7CWallet10LoadWalletERb + 155
8   hyperstake-qt                       0x0000000109bfcd34 _Z8AppInit2v + 39060
9   hyperstake-qt                       0x000000010992943d main + 6845
10  libdyld.dylib                       0x00007fff8fd505c9 start + 1

**Comment by presstab** [comment]
From the testing I have done, this is not caused from updating from one version to another. Probably is a bad DB write somewhere. To get rid of the error, loading a backup wallet should work, or you could even try -salvagewallet.
