### ISSUE TITLE
says 50 days to stake, passed 8.8 days, followed example in video, no staking yet.

### ISSUE THREAD

**Issue by seanauriti** [hyperstake/HyperStake#56]

**Comment by ponnanganni** [comment]
Hi, I'm not 100% sure but this mostly depends on the weight of the coins, more coins in a block means higher weight.

the minimum staking period is 8.8 days but it takes more time for a stake to actually happen, the smaller the buckets, the longer time it takes for a stake to occur.

**Comment by seanauriti** [comment]
its working, thanks for the answer.
