### ISSUE TITLE
Segmentation Fault on Raspberry Pi

### ISSUE THREAD

**Issue by jfldsf** [hyperstake/HyperStake#58]
I downloaded the raspberry pi executable from hyperstake.io and installed all of the dependencies. Now, when I try to run it, it says 'segmentation fault'.  When I do gdb, it outputs
#0  0xb6dedde0 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
No symbol table info available.
#1  0xb6dea4f4 in OPENSSL_cpuid_setup ()
   from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
No symbol table info available.
#2  0xb6fdf544 in call_init (l=<optimized out>, argc=argc@entry=1, 
    argv=argv@entry=0xbefff094, env=env@entry=0xbefff09c) at dl-init.c:72
        j = <optimized out>
        jm = <optimized out>
        addrs = <optimized out>
        init_array = <optimized out>
#3  0xb6fdf6a0 in call_init (env=<optimized out>, argv=<optimized out>, 
    argc=<optimized out>, l=<optimized out>) at dl-init.c:30
No locals.
#4  _dl_init (main_map=0xb6fff960, argc=1, argv=0xbefff094, env=0xbefff09c)
    at dl-init.c:120
        preinit_array = <optimized out>
        preinit_array_size = <optimized out>
        i = 4
#5  0xb6fcea24 in _dl_start_user () from /lib/ld-linux-armhf.so.3
        audit_list = 0x0
        _dl_rtld_libname2 = {name = 0x0, next = 0x0, dont_free = 0}
        library_path = 0x0
help plz

**Comment by presstab** [comment]
Which raspberry pi are you using?

**Comment by jfldsf** [comment]
Oh sorry, forgot to close it. I just installed Jessie instead of stretch, and it worked. Zero, by the way.
