### ISSUE TITLE
When I try to compile the CLI, it says 'nothing to be done for all-am' and hyperstaked doesn't show up.

### ISSUE THREAD

**Issue by jfldsf** [hyperstake/HyperStake#70]
I have an Orange Pi One, and I tried compiling the 'hyperstaked' on it. It's running Debian Jessie. When I try to run it with ./hyperstaked, it just doesn't show up. 
https://pastebin.com/gA8CDFtc
I tried deleting the folder and trying again, but it still didn't show up.

**Comment by presstab** [comment]
Looks like it compiled fine. Maybe you are confused and looking for `hyperstake-cli` but everything including the cli commands all run through `hyperstaked`

**Comment by jfldsf** [comment]
I don't know what I was thinking. Thanks
